# Clase 4

### Python open()
La función `open()` de Python nos retorna los contenidos de archivos como objetos de Python. Sus parametros principales son:
- file_name: ruta completa del archivo que queremos leer
- mode: este parametro especifica en que modo sera leido el archivo
    - “r”: Solo lectura(read-only), este es el valor por defecto
    - “w”: Este se usa para escribir sobre el archivo o lo crea si el archivo no existe
    - “a”: Se utiliza para hacer "append" al archivo, si el archivo no existe crea uno nuevo
    - “x”: Se utiliza para crear archivos
    - “t”: This string is used to handle files in text mode. By default, the open() function uses the text mode.

#### Creamos un archivo

In [1]:
nuevo_archivo = open("bioinformatica.txt", "x")

#### Leemos un archivo en modo escritura

In [1]:
archivo = open("bioinformatica.txt", "w")

## Utilizamos la funcion write para escribir
archivo.write("Bioindormatica USAC")
## Utilizamos la funcion close() para cerrar el archivos, 
## a partir de aca ya no se puede escribir en el archivo
archivo.close()

### Revisando el contenido de el archivo

In [3]:
archivo = open("bioinformatica.txt","r")
print(archivo.read())

Bioindormatica USAC

## XML
Permite almacenar datos de forma compatible entre múltiples sistemas(bases de datos, aplicaciones)

- XML es extensible: se puede extender a muchas areas de interés, se pueden crear formatos XML para codificar datos bioinformáticos.
- XML provee documentación: debido a que esta estructurado, es facil validar esa estructura
- XML se puede leer por humanos y máquinas

In [58]:
from xml.dom.minidom import parse, parseString, Node

```
<?xml version="1.0" encoding="UTF-8"?>
<Sequence>
    <accession>NM-171533</accession>
    <organism>
        <name>Caenorhabditis elegans</name>
        <description> Is a free-living transparent nematode about 1 mm in length[7] 
        that lives in temperate soil environments.</description>
    </organism>
    <sequence-data>
    agcacatgacatgagcagtgccccaaatgatgactgtgagatcgacaaggg
    aacaccttctaccgcttcactttttacaacgctgatgctcagtcaaccatcttcttct
    acagctgttttacagtgtacatattgtggaagctcgtgcacatcttcccaattgca
    aacatgtttattctg
    </sequence-data>
</Sequence>
```

<img src="xml.png">

Documentacion oficial (https://docs.python.org/3/library/xml.dom.html#dom-element-objects)

In [12]:
document = parse("caenorhabditis_elegans.xml")

In [13]:
document

In [14]:
print(document.version)
print(document.encoding)
print(document.standalone)

1.0
UTF-8
None

### Raiz del documento
Utilizamos la propiedad `documentElement` para obtener la raiz de el documento

In [15]:
document.documentElement

In [18]:
document.documentElement.tagName

'Sequence'

Para encontrar un elemento por el nombre del tag utilizamos la función `getelementById`

In [29]:
sequence = document.documentElement

In [34]:
for hijo in sequence.childNodes:
    print(hijo)

<DOM Text node "'\n'">
<DOM Element: accession at 0x7f6411701430>
<DOM Text node "'\n'">
<DOM Element: organism at 0x7f64117011f0>
<DOM Text node "'\n'">
<DOM Element: sequence-data at 0x7f6411701160>
<DOM Text node "'\n'">

In [39]:
organism = sequence.getElementsByTagName("organism")

In [47]:
organism[0].childNodes

[<DOM Text node "'\n    '">,
 <DOM Element: name at 0x7f64117013a0>,
 <DOM Text node "'\n    '">,
 <DOM Element: description at 0x7f6411701790>,
 <DOM Text node "'\n'">]

In [54]:
for hijo in organism[0].childNodes:
    print(hijo)

<DOM Text node "'\n    '">
<DOM Element: name at 0x7f64117013a0>
<DOM Text node "'\n    '">
<DOM Element: description at 0x7f6411701790>
<DOM Text node "'\n'">

In [57]:
organism[0].attributes

In [66]:
for hijo in organism[0].childNodes:
    if hijo.nodeType == Node.ELEMENT_NODE:
        print(hijo.childNodes[0].nodeValue)

Caenorhabditis elegans
 Is a free-living transparent nematode about 1 mm in length[7] that lives in temperate soil environments.

In [1]:
#Intalamos nuevas librerias solo correrlo 1 vez
!pip install xmltodict

Collecting xmltodict
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Installing collected packages: xmltodict
Successfully installed xmltodict-0.13.0

In [3]:
import xmltodict

In [4]:
with open("caenorhabditis_elegans.xml", "rb") as file:
    Sequence=xmltodict.parse(file)

In [5]:
print(Sequence)

{'Sequence': {'accession': 'NM-171533', 'organism': {'name': 'Caenorhabditis elegans', 'description': 'Is a free-living transparent nematode about 1 mm in length[7] that lives in temperate soil environments.'}, 'sequence-data': 'agcacatgacatgagcagtgccccaaatgatgactgtgagatcgacaaggg\naacaccttctaccgcttcactttttacaacgctgatgctcagtcaaccatcttcttct\nacagctgttttacagtgtacatattgtggaagctcgtgcacatcttcccaattgca\naacatgtttattctg'}}

**Ejercicio**: Imprimir el nombre y la descripción utilizado el diccionario
Investigar la funcion items del diccionario(esto viene en el examen!!)

In [12]:
## Tu codigo aqui: 

for key, valor in Sequence["Sequence"].items():
    if type(valor) == dict:
        for k, v in valor.items():
            print(key+"-->"+k+"-->"+str(v))
    else:
        print (key+"-->"+str(valor))

accession-->NM-171533
organism-->name-->Caenorhabditis elegans
organism-->description-->Is a free-living transparent nematode about 1 mm in length[7] that lives in temperate soil environments.
sequence-data-->agcacatgacatgagcagtgccccaaatgatgactgtgagatcgacaaggg
aacaccttctaccgcttcactttttacaacgctgatgctcagtcaaccatcttcttct
acagctgttttacagtgtacatattgtggaagctcgtgcacatcttcccaattgca
aacatgtttattctg

## CSV (Comma-Separated Values)
Para los archivos CSV vamos a utilizar pandas ya que es la forma mas facil de manejar este tipo de datos.

Es importante leer la documentacion de pandas con respecto a esta función ya que tiene multiples parametros.
[pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

In [1]:
import pandas as pd

In [2]:
covid_vacunacion = pd.read_csv("country_vaccinations.csv")

In [3]:
covid_vacunacion.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

In [8]:
covid_vacunacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86512 entries, 0 to 86511
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              86512 non-null  object
 1   iso_code                             86512 non-null  object
 2   date                                 86512 non-null  object
 3   total_vaccinations                   43607 non-null  float64
 4   people_vaccinated                    41294 non-null  float64
 5   people_fully_vaccinated              38802 non-null  float64
 6   daily_vaccinations_raw               35362 non-null  float64
 7   daily_vaccinations                   86213 non-null  float64
 8   total_vaccinations_per_hundred       43607 non-null  float64
 9   people_vaccinated_per_hundred        41294 non-null  float64
 10  people_fully_vaccinated_per_hundred  38802 non-null  float64
 11  daily_vaccinations_per_million       86213 non-null  float64
 12  vaccines                             86512 non-null  object
 13  source_name                          86512 non-null  object
 14  source_website                       86512 non-null  object
dtypes: float64(9), object(6)
memory usage: 9.9+ MB

In [9]:
covid_vacunacion.describe()

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,4.360700e+04,4.129400e+04,3.880200e+04,3.536200e+04,8.621300e+04,43607.000000,41294.000000,38802.000000,86213.000000
mean,4.592964e+07,1.770508e+07,1.413830e+07,2.705996e+05,1.313055e+05,80.188543,40.927317,35.523243,3257.049157
std,2.246004e+08,7.078731e+07,5.713920e+07,1.212427e+06,7.682388e+05,67.913577,29.290759,28.376252,3934.312440
min,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,5.264100e+05,3.494642e+05,2.439622e+05,4.668000e+03,9.000000e+02,16.050000,11.370000,7.020000,636.000000
50%,3.590096e+06,2.187310e+06,1.722140e+06,2.530900e+04,7.343000e+03,67.520000,41.435000,31.750000,2050.000000
75%,1.701230e+07,9.152520e+06,7.559870e+06,1.234925e+05,4.409800e+04,132.735000,67.910000,62.080000,4682.000000
max,3.263129e+09,1.275541e+09,1.240777e+09,2.474100e+07,2.242429e+07,345.370000,124.760000,122.370000,117497.000000

**Ejercicio** El archivo `diabetes2.csv` no tiene un header, se encuentra unicamente la data, hay que cargar el archivo y utilizar la lista `columnas`, ver en la documentacion, que parametros utilizar para cargar la data correctamente:

In [16]:
columnas = ["Pregnancies","Glucose","BloodPressure","SkinThickness",
            "Insulin","BMI","DiabetesPedigreeFunction","Age","Outcome"]

In [17]:
import pandas as pd

In [18]:
## Tu codigo aqui: 
data=pd.read_csv("diabetes2.csv",header=None, names=columnas)
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

## JSON 
- Es muy comprensible para el humano por su formato
- Es tan fácil de comprender que se describe solo debido a su formato
- Los archivos JSON tienen tipos de datos:
    - String
    - Number
    - Boolean
    - Null
    - Object
    - Array

In [20]:
import json

In [21]:
data = {
    "nombre": "bioinformatica",
    "hora_inicio": 7,
    "hora_fin": 10
}

In [22]:
with open("data_file.json", "w") as write_file:
    json.dump(data, write_file)

In [24]:
### Cargando un archivo
with open("caenorhabditis_elegans.json", "r") as read_file:
    data = json.load(read_file)
    
print(data)

{'organism': {'name': 'Caenorhabditis elegans', 'description': 'Is a free-living transparent nematode about 1 mm in length[7] that lives in temperate soil environments', 'sequence': 'agcacatgacatgagcagtgccccaaatgatgactgtgagatcgacaagggaacaccttctaccgcttcactttttacaacgctgatgctcagtcaaccatcttcttctacagctgttttacagtgtacatattgtggaagctcgtgcacatcttcccaattgcaaacatgtttattctg'}}